services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    depends_on:
      - mongo

  frontend:
    build: 
      context: ./frontend
      args:
        - VITE_BASE_URL=http://localhost:3000
        - VITE_NODE_ENV=development
    ports:
      - "5000:80"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
   


volumes:
  mongo-data:

